### ISSUE TITLE
from harvest.dataclasses import * error

### ISSUE THREAD

**Issue by gshel** [bradbase/python-harvest_apiv2#13]
Hey thanks for creating this library! It's come in very handy for my team and we appreciate all your hard work.

In the[ README.md](https://github.com/bradbase/python-harvest_apiv2/blob/master/README.md), users are instructed to use the following import statement:
```
from harvest.dataclasses import *
```

However, there is no file called `dataclasses` in the harvest directory -- there is, however, a file called `harvestdataclasses` in the harvest dir. I'd like to update the README accordingly; see image below for verification.

![image](https://user-images.githubusercontent.com/35184207/96196601-c516b500-0f1d-11eb-9613-1342d08360b0.png)

Additionally, the [package's Pypi page](https://pypi.org/project/python-harvest-apiv2/) has a typo in its [homepage url](https://github.com/bradbase/python-harvest-apiv2), causing it to 404.

I'll be opening a PR addressing both of these shortly🎉

**Comment by bradbase** [comment]
Hi @gshel 

Thanks for the feedback. It's not easy to tell who's actually using the library and how much impact it's having.

I've tried to get in touch with the TAOS team WRT a reporting project related to this library to see if there are any feature I need to complete to help out. In any case I'm glad it's had a positive impact for your project.

And big thanks for picking up the errors and the PR. I'll attempt to publish a build this afternoon (eg; in the next few hours).

**Comment by bradbase** [comment]
@gshel 

I have created and published a new release. 1.6.0

harvest.dataclasses changed to harvest.harvestdataclasses three times in README.md so I updated the other two.

Thanks again for your input. :D
