### ISSUE TITLE
Project name doesn't match repository name

### ISSUE THREAD

**Issue by bradbase** [bradbase/python-harvest_apiv2#16]
FYI: @ptitiano @gshel @swiftech @jonathansaetre @grugnog @thefirstofthe300 

Time to own up to an embarrassing error I appear to have made early on and have just discovered.

I have attempted to make a conda package for this project and found the name of the project doesn't align with the name of the repo.

Repo;
```
python-harvest_apiv2
```
Current project name;
```
python-harvest-apiv2
```

Although not _required_ it would make Anaconda packaging easier if the names align. Such a change, however, will make the package appear in PyPi under the different name.

How severely would such a change impact any of you?

**Comment by jonathansaetre** [comment]
Hey
I appreciate the good work!
I say do it :)

**Comment by bradbase** [comment]
Well... There you go.

I made the change and it doesn't make any difference.
