### ISSUE TITLE
reports: timeframe: wrong dict keys

### ISSUE THREAD

**Issue by ptitiano** [bradbase/python-harvest_apiv2#4]
Hello @bradbase ,
timeframe() returns a dict with 'from' and 'to' keys, but time_entries() subsequent calls in detailed_time() expects 'from_date' and 'to_date' arguments, causing the following exception to be raised:
    TypeError: time_entries() got an unexpected keyword argument 'from'

Can we fix this, please?
Thanks
Patrick

**Comment by bradbase** [comment]
Fixed in 1.2.0
